### ISSUE TITLE
Action Required: Update your Braintree SDK version by May 1

### ISSUE THREAD

**Issue by ejsmithgem** [angelleye/gravity-forms-braintree#19]
I confirmed that this plugin will no longer work when this Braintree update goes live because the PHP version is too low.

This is the only good plugin for our needs, any advice on how to update the PHP version to be compatible?

From Braintree:
"We will be updating our root SSL provider for API traffic to align with security standards starting April 1, 2020 in sandbox and May 1, 2020 in production. To avoid interruption to your processing, please update your SDK version to the appropriate minimum versions specified on this page."

https://developers.braintreepayments.com/reference/general/best-practices/php#server-sdk-versions

**Comment by angelleye** [comment]
I'm a little confused.  Are you saying that you need to update the PHP version on your server?

**Comment by angelleye** [comment]
I have a ticket created on our side to look into this and make any necessary adjustments.

We're actually working to add ACH support with Braintree into this plugin, so we'll release this at the same time as that (very soon.)

Thanks for the feedback!

**Comment by ejsmithgem** [comment]
I'm confused too. I guess I need to update the Braintree PHP SDK to at least version 3.8.0. I don't know how that is done when I'm using a plugin to handle it. When using your plugin to test payments on Braintree Sandbox, it no longer works and I see that its using "Braintree PHP SDK 2.26.0". 

Using this plugin to make production payments still works because production hasn't gotten the update yet, but Sandbox no longer accepts payments using this plugin so I'm assuming it has something to do with the Braintree PHP SDK included in the plugin (though I barely understand what I'm doing here, I'm not a Wordpress or PHP expert) 

Thanks very much for the reply, I wasn't expecting one at all! This is easily the best option for us in terms of making Braintree payments, especially with Gravity Forms.

**Comment by angelleye** [comment]
We're going to review our plugin integration and see if we need to make an adjustment there.  If so, we'll get it done very soon.

It's possible, though, that the PHP version on your server is not allowing the proper use of protocols that Braintree will require when they flip that switch.  

What version of PHP are you running right now?

**Comment by angelleye** [comment]
Also, can you check what version of OpenSSL you're running?

**Comment by ejsmithgem** [comment]
The server is on PHP 7.X. Ill have a look into the SSL

**Comment by angelleye** [comment]
Okay, if you're on 7.x then you should be fine.  We'll check the SDK integration and update you accordingly.

**Comment by ejsmithgem** [comment]
Very much appreciated thank you

**Comment by deepakmaurya** [comment]
@ejsmithgem We just released a new version, You can update your plugin with the help of [Angell EYE updater](https://www.angelleye.com/product/angelleye-updater-wordpress/). 
Thanks
