### ISSUE TITLE
not saving settings

### ISSUE THREAD

**Issue by fonderco** [angelleye/gravity-forms-braintree#29]
I put in my Merchant ID, Public Key, Private Key... But it doesn't save and I get errors everytime I submit a credit card.

Ideas?

**Comment by j3ph** [comment]
I'm having the exact same issue.

**Comment by drewangell** [comment]
Hey guys, sorry we never replied here.  We use Jira primarily and neglected our GitHub issue comments.  We're fixing that so it won't happen again.

We released an update recently that makes our stuff fully compatible with the latest version of GF, and this type of issue shouldn't be happening.  If you want to try the latest version it should be good, but if not just let me know and we'll get right on it.  I don't have any other recent reports of problems, though.  Thanks!
