### ISSUE TITLE
GFB-44 - Full Support for 3D Secure

### ISSUE THREAD

**Issue by drewangell** [angelleye/gravity-forms-braintree#40]
# Story

As a merchant using Braintree in Gravity Forms, I need full support for 3D Secure, so that I can launch for buyers in countries where 3DS is required.

# Details

I believe Braintree has 3DS integrated, but we may just need to adjust some things in our API calls in order to make it work.

## Documentation

*   [![](https://www.braintreepayments.com/images/favicon.png)3D Secure 2 | Braintree Payments](https://www.braintreepayments.com/features/3d-secure)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue has a bounty of $25.00 ready to be claimed!**

- If you are a Contributor and would like to complete this task to claim the bounty you can **Start Work** on the [GitCommits issue details page](https://app.gitcommits.com/issue/gfb-44-full-support-for-3d-secure).
- If you would like to see this issue completed more quickly, please **Add Funding** to the bounty on the [GitCommits issue details page](https://app.gitcommits.com/issue/gfb-44-full-support-for-3d-secure).
- More open bounties are available in the [GitCommits Issue Explorer](https://app.gitcommits.com/explorer)
- Questions? Review our [FAQ](https://www.gitcommits.com/faq)

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
