### ISSUE TITLE
Not available on wp.org

### ISSUE THREAD

**Issue by ethanclevenger91** [angelleye/gravity-forms-braintree#41]
Contrary to the README, I can't find this on the WP.org plugin repo.

**Comment by ethanclevenger91** [comment]
The link in the project short description actually goes to the plugin directory and says the plugin is closed, last updated 6 years ago.

**Comment by drewangell** [comment]
Hi, sorry I never got back to you on this.  We forked this repo from another dev that was no longer maintaining it.  We had it working, but people are telling me it doesn't work anymore.  However, I'm not able to reproduce any problem.

I can certainly fix the readme.  Are you having any other issues with functionality in general?

**Comment by ethanclevenger91** [comment]
@drewangell it's not a matter of functionality or a problem with the README. You submitted this plugin to the WP.org plugin repo [here](https://wordpress.org/plugins/angelleye-gravity-forms-braintree/) and it was closed in 2019 due to "Guidelines Violations". Would be nice to see that back up.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
