### ISSUE TITLE
ACH form validation issue when hidden

### ISSUE THREAD

**Issue by mgithens** [angelleye/gravity-forms-braintree#43]
When the ACH form is hidden it should not require validation of it's fields but it currently does. The following illustrates the issue with requiring validation even when the form is hidden:

We created a gravity form containing both payment options, CC or ACH. The payee may choose to toggle between one or the other via a radio button option. If they choose ACH then the Credit Card form will be hidden and the ACH form will be visible. The form works in this case, however, if the user chooses to submit a payment via the CC form then the form fails to validate since the ACH form requires all the fields to be completed even though it is hidden.

Obviously we could create to separate forms to get around this issue but that is not the desired approach.

**Comment by devchristina2** [comment]
Hi @mgithens,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
